services:
  etl:
    build: ./etl
    env_file:
      - .env.example
    command: tail -F anything
    depends_on:
      - postgres
      - elastic
    expose:
      - 8000

  postgres:
    image: postgres:13
    env_file:
      - .env.example
    volumes:
      - $HOME/postgresql/data:/var/lib/postgresql/data
    expose:
      - 5432
#    ports:
#      - '5432:5432'

  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.7.0
    environment:
      - discovery.type=single-node
    expose:
      - 9200
#    ports:
#      - '0.0.0.0:9201:9201'

